### ISSUE TITLE
Como e onde inserir a "tag" para o plugin SIMULADOR-FRETE-VM-3 no template?

### ISSUE THREAD

**Issue by aespa** [luizwbr/Simulador-Frete-VM-3#1]
Como e onde inserir a "tag" para o plugin SIMULADOR-FRETE-VM-3 no template?

**Comment by luizwbr** [comment]
@aespa, fica lá em /templates/SEU_TEMPLATE/html/com_virtuemart/productdetails/default.php.

A tag tem que ser exatamente esta: <simulador/>

**Comment by aespa** [comment]
Certo. Consegui implementar. Obrigado!

**Comment by rafaelbizerra** [comment]
Pessoal estou precisando de uma ajuda,  ..... qual "tag"  eu devo colocar no  ".../productdetails/default.php" ... e em que lugar do "linha"  ".../productdetails/default.php" .... eu devo inserir a tag indicada ?? ...... 
mto obrigado
