### ISSUE TITLE
E quando nao tem esse caminho SEU_TEMPLATE/html/com_virtuemart

### ISSUE THREAD

**Issue by tasf12** [luizwbr/Simulador-Frete-VM-3#2]
Bom dia, no meu templade nao tem esse caminho , na verdade nao tem a pasta com_virtuemart dentro da pasta templates(templates/SEU_TEMPLATE/html/com_virtuemart/productdetails/default.php.)  e os productdetails/default.php fica components/com_virtuemart/views/productdetails/tmpl/default.php
 é a mesma coisa?, pois tentei criar a tag la mas nada aconteceu, alguma dica?

precisava de um de algo q integrasse o virtueMart 3.4 com os correios, ou simulasse o valor do frete com base nos correios para somar o valor da compra, alguma dica?

Desde já obrigado por qualquer ajuda.

**Comment by joaoferraz0701** [comment]
Bom dia tasf12,
Como é que vc cria a tag pra colocar lá? Qual a linha de comando?
Obrigado.

**Comment by tasf12** [comment]
Bom dia joaoferraz0701, dentro do plugin, após instalado tem um campo especifico, onde por padrão já vem como 'simulador', mas vc pode alterar para o nome que vc quiser, esta é a tag que sera usada na códificação.

**Comment by joaoferraz0701** [comment]
Bom dia! Eu sou meio leigo nisso. Eu vi a tag no plugin, mas gostaria de saber como inserir esta tag no arquivo default.php.
Abç!

**Comment by tasf12** [comment]
segue o link com a  explicação do desenvolvedor; 
https://github.com/luizwbr/Simulador-Frete-VM-3/issues/1
 exemplo de tag em html: '<sua_tag_do_plugin>'

**Comment by joaoferraz0701** [comment]
Coloquei` assim e nada aconteceu:
![image](https://user-images.githubusercontent.com/5217722/60271710-3796f800-98c9-11e9-8c2a-7ffcaab8355a.png)

Seria isto? O plugin está instalado e ativado. Quando coloco só a palavra 'simulador' dentro do div ela aparece no local que eu quero que apareça dentro da pagina do produto.

**Comment by tasf12** [comment]
eu também estou com esse problema, aguardando o desenvolvedor da uma help para poder contornar essa situação.

**Comment by tasf12** [comment]
Analisando o código fonte do plugin descobrir uma coisa tente por a tag no local que deseja assim :<silmulador/> (tag com auto fechamento < Sua_tag />) acho q assim aparecerá o simulador.

**Comment by joaoferraz0701** [comment]
funcionou!!! Valeu cara!

**Comment by tasf12** [comment]
joaoferraz0701 além de aparecer o plugin na tela, você conseguiu fazer a simulação dos valores?

**Comment by joaoferraz0701** [comment]
Sim, esta funcionando
